--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/RulesUI
build-by-default: true
branches:
- main
projects:
  RulesUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^2.0.0
    - src: thebigcrafter/Hydrogen/Hydrogen
      version: ^1.0.0
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
...
