--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/RulesUI
build-by-default: true
branches:
- main
projects:
  RulesUI:
    path: ""
    libs:
    - src: jojoe77777/FormsUI/FormsUI
      version: ^1.1.2
    - src: thebigcrafter/Hydrogen/Hydrogen
      version: ^1.0.0
...
