name: RulesUI
main: NurAzliYT\RulesUI\Main
api: 5.0.0
version: 1.0.0
authors: [NurAzliYT, NurAzli, MauslaGames]
description: Shows server rules in UI form
website: https://github.com/NurAzliYT/RulesUI

permissions:
  rulesui.rules:
    description: Permission to use RulesUI
    default: true
