---
# RulesUI plugin config
# Created by NurAzliYT, MauslaGames and Hounly Store
# Use "{player}" to display player name
# Use "&" as formatting codes
# Use "\n" to break into a new line

##### DANGER ZONE #####
# Don't Change Config Version!
config-version: "1.0"
#######################

##### COMMAND SETTINGS #####
command-desc: ""
# Add command aliases for /rules command (Leave empty if you don't want to add command aliases)
# Do not use "/" in front of the commands!
command-aliases: [r]
#############################

# Set the RulesUI title here:
title: "RulesUI"

# Set the RulesUI content here:
content: "Change in config.yml!"

# Set the KygekRulesUI button here:
button: "Ok"
...
